#!/usr/bin/env bash

keychain="$(which keychain)"

case $1 in
  start)
    $keychain --quick --quiet $(find $HOME/.ssh/ -regex .*id_rsa.* ! -name *.pub)
    ;;
  stop)
    $keychain -k all
    ;;
esac
