#!/usr/bin/env bash

set -e

postman_path="/opt/Postman"
backup_path="/opt/Postman.1.bk"

if [ -d $postman_path ]; then
  rm -fr $backup_path
  mv $postman_path $backup_path
  echo "Backup previous version to $backup_path"
fi

echo "Installing Postman..."
wget -q https://dl.pstmn.io/download/latest/linux?arch=64 -O - \
  | sudo tar xzf - -C "$(dirname $postman_path)"

sudo ln -sf $postman_path/Postman /usr/local/bin/postman

cat>"$HOME/.local/share/applications/Postman.desktop"<<EOF
[Desktop Entry]
Categories=Development;
Comment=Postman
Encoding=UTF-8
Exec=postman
Icon=$postman_path/app/resources/app/assets/icon.png
Name=Postman
Terminal=false
Type=Application
EOF
