---
- name: dotfiles | create standard dirs
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ my_bin }}"
    - "{{ my_src }}"
    - "{{ home_dir}}/go"

- name: dotfiles | install .*
  copy:
    src: "{{ item }}"
    dest: "{{ home_dir}}/.{{ item | basename }}"
    backup: yes
  with_fileglob:
    - dotfiles/*

- name: dotfiles | tmux battery
  copy:
    src: battery.py
    dest: "{{ my_bin }}/battery"
    mode: 0755
