---
- name: dotfiles | prepare pathogen
  file: >
    path={{ item }}
    state=directory
    recurse=yes
  with_items:
    - "{{ vim_autoload }}"
    - "{{ vim_bundle }}"
    - "{{ my_bin }}"
    - "{{ my_src }}"
  tags: pathogen

- name: dotfiles | pathogen infect
  get_url: >
    url=https://tpo.pe/pathogen.vim
    dest={{ vim_autoload }}
  tags: pathogen

- name: dotfiles | install vim plugins
  git: >
    repo={{ item }}
    dest={{ vim_bundle }}/{{ item | basename | replace('.git', '') }}
  with_items:
    - "{{ git_repos }}"
  tags: pathogen

- name: dotfiles | install dots
  copy: >
    src={{ item }}
    dest={{ home_dir}}/.{{ item | basename }}
    backup=yes
  with_fileglob:
    - dotfiles/*
  tags: dotfiles

- name: dotfiles | tmux battery
  copy: >
    src=battery
    dest={{ home_dir }}/bin/battery
    mode=0755
  tags: dotfiles
