---
- name: dotfiles | create standard dirs
  file: >
    path={{ item }}
    state=directory
    recurse=yes
  with_items:
    - "{{ my_bin }}"
    - "{{ my_src }}"
  tags: dotfiles

- name: dotfiles | install .*
  copy: >
    src={{ item }}
    dest={{ home_dir}}/.{{ item | basename }}
    backup=yes
  with_fileglob:
    - dotfiles/*
  tags: dotfiles

- name: dotfiles | tmux battery
  copy: >
    src=battery
    dest={{ my_bin }}/battery
    mode=0755
  tags: dotfiles
