---
- name: vim | vim-nox
  package: >
    name=vim-nox
    state=present
  tags: vim
  become: yes

- name: vim | update-alternatives
  alternatives: >
    name=editor
    path=/usr/bin/vim.nox
  when: ansible_distribution == "Ubuntu"
  tags: vim
  become: yes

- name: pathogen | prepare pathogen
  file: >
    path={{ item }}
    state=directory
    recurse=yes
  with_items:
    - "{{ vim_autoload }}"
    - "{{ vim_bundle }}"
  tags: ['vim', 'pathogen']

- name: pathogen | infect
  get_url: >
    url=https://tpo.pe/pathogen.vim
    dest={{ vim_autoload }}
  tags: ['vim', 'pathogen']

- name: pathogen | install vim plugins
  git: >
    repo={{ item }}
    dest={{ vim_bundle }}/{{ item | basename | replace('.git', '') }}
  with_items:
    - "{{ vim_plugins }}"
  tags: ['vim', 'pathogen', 'skip_ansible_lint']
