---
- name: insomnia | install
  apt: >
    deb=https://downloads.insomnia.rest/linux/insomnia_4.2.9_amd64.deb
  tags: insomnia
  become: yes

- name: insomnia | update .desktop file
  lineinfile: >
    dest=/usr/share/applications/Insomnia.desktop
    line=Categories=Development;
    state=present
  tags: insomnia
  become: yes
