---
#
# https://github.com/lwfinger/rtlwifi_new - still rubbish
#
- name: realtek wifi | add config
  copy: >
    src=rtl8192ee.conf
    dest=/etc/modprobe.d/rtl8192ee.conf
  tags: realtek
  become: yes

# disable wifi
- name: realtek wifi | blacklist module
  lineinfile: >
    dest=/etc/modprobe.d/blacklist.conf
    line='blacklist rtl8192ee'
    backup=yes
  tags: realtek
  become: yes
