---
- name: docker | add key
  apt_key: >
    keyserver=p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D
  tags: docker
  become: true

- name: docker | install python-apt
  pip: >
    name=python-apt
    state=latest
  tags: docker
  become: true

- name: docker | install docker repo
  apt_repository: >
    filename=docker
    repo="deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    update_cache=yes
    state=present
  tags: docker
  become: true

- name: docker | install docker
  package: >
    name=docker-engine
    state=latest
  tags: docker
  become: true
