---
- name: docker | add key
  apt_key: >
    keyserver=p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D
  tags: docker
  become: yes

- name: docker | install python-apt
  pip: >
    name=python-apt
    state=latest
  tags: docker
  become: yes

- name: docker | install docker repo
  apt_repository: >
    filename=docker
    repo="deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    update_cache=yes
    state=present
  tags: docker
  become: yes

- name: docker | install docker
  package: >
    name=docker-engine=1.11.2-0~{{ ansible_distribution_release }}
  tags: docker
  become: yes

- name: docker | add docker group
  group: >
    name=docker
    state=present
  tags: docker
  become: yes

- name: docker | update group
  user: >
    name={{ lookup('env','USER') }}
    append=yes
    groups=docker
  tags: docker
  become: yes

- name: docker | start
  service: >
    name=docker
    state=started
    enabled=yes
  tags: docker
  become: yes
