---
- name: editor | vim-nox
  package: >
    name=vim-nox
    state=latest
  tags: editor
  become: true

- name: editor | update-alternatives
  alternatives: >
    name=editor
    path=/usr/bin/vim.nox
  when: ansible_distribution == "Ubuntu"
  tags: editor
  become: true
