---
- block:
  - name: base | core packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - alsa-base
      - build-essential
      - dunst
      - feh
      - i3
      - i3blocks
      - intel-microcode
      - j4-dmenu-desktop
      - libffi-dev
      - libssl-dev
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings
      - pavucontrol
      - pulseaudio
      - pulseaudio-module-bluetooth
      - rxvt-unicode
      - thunar
      - ubuntu-drivers-common
      - x11-xserver-utils
    become: yes

  - name: base | dkms
    package:
      name: dkms
      state: present
    when: ansible_virtualization_role == "guest"
    become: yes

  tags:
    - base
    - binaries
