---
- block:
  - name: binaries | utils
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ binaries }}"
    become: yes

#  - name: binaries | unetbootin fix
#    lineinfile:
#      dest: /usr/share/applications/unetbootin.desktop
#      regexp: '^Exec'
#      line: "Exec=/usr/bin/unetbootin -s"
#      state: present
#    become: yes

  tags:
    - binaries
