---
- block:
  - name: binaries | utils
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ binaries }}"
    become: yes

  - name: binaries | dkms
    package:
      name: dkms
      state: present
    when: ansible_virtualization_role == "guest"
    become: yes

  tags:
    - binaries
