---
- block:
  - name: binaries | utils
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ binaries }}"

  - name: binaries | guest specific packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - dkms
      - linux-headers-generic
      - openssh-server
    when: ansible_virtualization_role == "guest"

  - name: binaries | x packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ xbinaries }}"
    when: ansible_virtualization_role == "host"

  become: yes
  tags:
    - base
    - binaries
    - wsl
