---
- block:
  - name: binaries | utils
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ binaries }}"
    become: yes

  - name: binaries | guest specific packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - dkms
      - openssh-server
    when: ansible_virtualization_role == "guest"
    become: yes
  tags:
    - base
    - binaries
