---
- block:
  - name: nvim | install neovim
    package:
      name: neovim
      state: present
    become: yes

  - name: nvim | update-alternatives editor
    alternatives:
      name: editor
      path: /usr/bin/nvim
    become: yes

  - name: nvim | update-alternatives vi
    alternatives:
      name: vi
      path: /usr/bin/nvim
    become: yes

  - name: nvim | create .config dirs
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
    with_items:
      - "{{ home_dir }}/.config/nvim/autoload"
      - "{{ home_dir }}/.config/nvim/plugged"

  - name: nvim | install plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ home_dir }}/.config/nvim/plugged"

  - name: nvim | install config
    copy:
      src: "{{ item }}"
      dest: "{{ home_dir }}/{{ item }}"
      backup: yes
    with_items:
      - .config/nvim/init.vim

  tags:
    - base
    - vim
    - editor
    - wsl
