---
- include_tasks: sudo.yml
  tags:
    - base
    - sudo
    - wsl

- include_tasks: binaries.yml
  tags:
    - base
    - binaries
    - wsl

- include_tasks: editor.yml
  tags:
    - base
    - vim
    - editor
    - wsl

- include_tasks: dotfiles.yml
  tags:
    - base
    - dots
    - dotfiles
    - wsl

- include_tasks: dropbox.yml
  tags:
    - never
    - dropbox

- include_tasks: docker.yml
  tags:
    - docker
    - wsl

- include_tasks: java-openjdk.yml
  tags:
    - java
    - wsl

- include_tasks: vscode.yml
  tags:
    - never
    - vscode

- include_tasks: dbeaver.yml
  tags:
    - never
    - dbeaver

- include_tasks: i3wm.yml
  tags:
    - never
    - i3

- include_tasks: fonts.yml
  tags:
    - never
    - fonts
    - i3

- include_tasks: chrome.yml
  tags:
    - never
    - chrome

- include_tasks: keepassxc.yml
  tags:
    - never
    - kpxc

- include_tasks: mpd.yml
  tags:
    - never
    - mpd

- include_tasks: xubuntu1804.yml
  tags:
    - xubuntu

- include_tasks: k8s-tools.yml
  tags:
    - never
    - k8s
    - wsl

- include_tasks: aws.yml
  tags:
    - never
    - aws
    - wsl

- include_tasks: aws-okta.yml
  tags:
    - never
    - aws-okta
    - wsl

- include_tasks: hashicorp.yml
  tags:
    - never
    - hashicorp
    - hashi
    - hash
    - wsl

- include_tasks: next.yml
  tags:
    - never
    - next
