---
- include_tasks: sudo.yml
  tags:
    - base
    - sudo
    - wsl

- include_tasks: binaries.yml
  tags:
    - base
    - binaries
    - wsl

- include_tasks: editor-neovim.yml
  tags:
    - base
    - vim
    - editor
    - wsl

- include_tasks: dotfiles.yml
  tags:
    - base
    - dots
    - dotfiles
    - wsl

- include_tasks: dropbox.yml
  tags:
    - dropbox
  when: ansible_virtualization_role == "host"

- include_tasks: docker.yml
  tags:
    - docker
    - wsl

- include_tasks: java-openjdk.yml
  tags:
    - java
    - wsl

- include_tasks: vscode.yml
  tags:
    - never
    - vscode
  when:
    - ansible_virtualization_role == "host"

- include_tasks: dbeaver.yml
  tags:
    - never
    - dbeaver
  when:
    - ansible_virtualization_role == "host"

- include_tasks: i3wm.yml
  tags:
    - never
    - i3
  when:
    - ansible_virtualization_role == "host"

- include_tasks: fonts.yml
  tags:
    - never
    - fonts
    - i3

- include_tasks: chrome.yml
  tags:
    - never
    - chrome
  when:
    - ansible_virtualization_role == "host"

- include_tasks: keepassxc.yml
  tags:
    - never
    - kpxc
  when:
    - ansible_virtualization_role == "host"

- include_tasks: mpd.yml
  tags:
    - never
    - mpd
  when:
    - ansible_virtualization_role == "host"

- include_tasks: 16.04.yml
  tags:
    - xubuntu
  when:
    - ansible_virtualization_role == "host"
    - ansible_product_version == "ThinkPad T440"
    - ansible_distribution_version = "16.04"

- include_tasks: 18.04.yml
  tags:
    - xubuntu
  when:
    - ansible_virtualization_role == "host"
    - ansible_product_version == "ThinkPad T440"
    - ansible_distribution_version = "18.04"

- include_tasks: 20.04.yml
  tags:
    - xubuntu
  when:
    - ansible_virtualization_role == "host"
    - ansible_product_version == "ThinkPad T440"
    - ansible_distribution_version = "20.04"

- include_tasks: k8s-tools.yml
  tags:
    - never
    - k8s

- include_tasks: aws.yml
  tags:
    - never
    - aws

- include_tasks: aws-okta.yml
  tags:
    - never
    - aws-okta

- include_tasks: hashicorp.yml
  tags:
    - never
    - hashicorp
    - hashi
    - hash

- include_tasks: groovy-lang.yml
  tags:
    - never
    - groovy

- include_tasks: next.yml
  tags:
    - never
    - next
  when:
    - ansible_virtualization_role == "host"
