---
- block:
  # depends on k8s-tools
  # NOTE: downgraded Docker to 18.06.0-ce to get v0.30.0 working
  - name: install minikube
    shell: "curl -Lo minikube {{ minikube_url }} && chmod +x minikube && sudo cp minikube /usr/local/bin/ && rm minikube"
    args:
      creates: /usr/local/bin/minikube
      warn: no

  - name: start minikube
    command: "minikube start --vm-driver=none --memory=8192"
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    args:
      creates: "{{ home_dir }}/.minikube"

  - name: confirm perms are set correctly
    file:
      path: "{{ item }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      recurse: yes
    with_items:
      - "{{ home_dir }}/.minikube"
      - "{{ home_dir }}/.kube"

  become: yes
  tags: minikube

