---
- block:
  - name: modify mpd directory permissions
    file:
      path: "{{ item }}"
      owner: "{{ user }}"
      recurse: yes
    with_items:
      - /var/log/mpd
      - /run/mpd
      - /var/lib/mpd
    become: yes

  tags: mpd

