---
# Next browser - https://github.com/atlas-engineer/next

- block:
  - name: next | dependencies
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - sbcl
      - libwebkit2gtk-4.0-dev
      - sqlite
      - libfixposix-dev
      - xclip
    become: yes

  - name: next | install
    apt:
      deb: https://next.atlas.engineer/static/release/next_1.3.4_amd64.deb
    tags: next
    become: yes
  tags:
    - next
