# ThinkPad T440 specific
---
# https://github.com/lwfinger/rtlwifi_new - still rubbish
- name: thinkpad | realtek wifi config
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/modprobe.d/rtl8192ee.conf
  become: yes
  tags: realtek

# disable wifi
- name: thinkpad | realtek wifi blacklist module
  lineinfile:
    dest: /etc/modprobe.d/blacklist.conf
    line: 'blacklist rtl8192ee'
    backup: yes
  become: yes
  tags: realtek

- name: thinkpad | install uswsusp
  package:
    name: uswsusp
    state: present
  become: yes
  tags: hibernate

# https://ubuntuforums.org/showthread.php?t=2332834
- name: thinkpad | enable hibernation
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    backup: yes
  with_items:
    - etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla
  become: yes
  tags: hibernate
