---
# xfce themes
- name: xfce | numix ppa
  apt_repository:
    repo: "ppa:numix/ppa"
    update_cache: yes
    state: present
  become: yes

- name: xfce | themes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gtk2-engines-murrine
    - numix-gtk-theme
    - numix-icon-theme
    - numix-icon-theme-circle
  become: yes

