---
- name: reload sysctl
  service:
    name: procps
    state: restarted
  become: yes

- name: merge xresources
  command: xrdb -merge $HOME/.Xresources

- name: restart pulse audio
  command: pulseaudio -k