---
- block:
  - name: dbeaver | install
    apt:
      deb: https://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb
    become: yes

  when: ansible_virtualization_role == "host"
  tags:
    - dbeaver
