---
- block:
  - name: docker | install docker
    package:
      name: docker.io
      state: present

  - name: docker | add docker group
    group:
      name: docker
      state: present

  - name: docker | update group
    user:
      name: "{{ lookup('env','USER') }}"
      append: yes
      groups: docker

  - name: docker | override.conf dir
    file:
      name: "{{ item }}"
      state: directory
      recurse: yes
    with_items:
      - /etc/systemd/system/docker.service.d
    when:
      - ansible_virtualization_role == "guest"

  - name: docker | write override.conf
    copy:
      src: "{{ item }}"
      dest: "/{{ item }}"
      backup: yes
    with_items:
      - etc/systemd/system/docker.service.d/override.conf
    when:
      - ansible_virtualization_role == "guest"
    notify: restart docker

  - name: docker | start
    service:
      name: docker
      state: started
      enabled: yes
    when:
      - ansible_kernel is not search("Microsoft")

  - name: docker | install docker-compose
    package:
      name: docker-compose
      state: present
    when:
      - ansible_kernel is not search("Microsoft")

  become: yes
  tags: docker
