---
- block:
  - name: dotfiles | create standard dirs
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ my_src }}"
      - "{{ home_dir }}/go"

  - name: dotfiles | install .*
    copy:
      src: "{{ item }}"
      dest: "{{ home_dir }}/{{ item | basename }}"
      backup: yes
    with_fileglob:
      - .*
    notify: merge xresources

  tags:
    - base
    - dotfiles
    - dots
    - wsl
