---
- name: dropbox
  block:
  - name: dropbox | increase watches
    copy:
      src: etc/sysctl.d/60-fs-inotify-max_user_watches.conf
      dest: /etc/sysctl.d/60-fs-inotify-max_user_watches.conf
    notify: reload sysctl

  # https://bugs.launchpad.net/ubuntu/+source/nautilus-dropbox/+bug/1546176
  - name: dropbox | install
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - nautilus-dropbox
      - thunar-dropbox-plugin

  when: ansible_virtualization_role == "host"
  become: yes
  tags:
    - dropbox
