---
- block:
  - name: mpd | install
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - mpd

  - name: mpd | modify directory permissions
    file:
      path: "{{ item }}"
      owner: "{{ user }}"
      recurse: yes
    with_items:
      - /var/log/mpd
      - /run/mpd
      - /var/lib/mpd

  become: yes
  when: ansible_virtualization_role == "host"
  tags: mpd

