---
- block:
  - name: vpn | cisco
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ cisco_vpn }}"

  # ppa was deleted: https://github.com/dlenski/openconnect/issues/84
  - name: vpn | patched openconnect ppa
    apt_repository:
      repo: "ppa:lenski/openconnect-gp"
      update_cache: yes
      state: absent

  - name: vpn | openconnect with gp
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ globalprotect_vpn }}"

  become: yes
  when:
    - ansible_virtualization_role == "host"
  tags: vpn
